set_active_schedule:
  target:
    entity:
      integration: themo
      domain: climate
  fields:
    schedule_name:
      description: Name of the schedule to set.
      example: 'Work week comfort'
      required: true
      selector:
        text:
